<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>

        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ServerGarbageCollection>true</ServerGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>

        <StripSymbols>true</StripSymbols>
        <OptimizationPreference>Size</OptimizationPreference>
        <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
        <IlcDisableReflection>false</IlcDisableReflection>
        <DebuggerSupport>false</DebuggerSupport>
        <EventSourceSupport>false</EventSourceSupport>
        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
        <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PensionCalculationEngine.Domain\PensionCalculationEngine.Domain.csproj" />
    </ItemGroup>

</Project>
